// German UI strings for the auth feature. Single-locale app — plain constants,
// no i18n machinery (per the authoritative plan).
export const authCopy = {
  eyebrow: "DÖNER-KOMMANDO LEIPZIG",
  heading: "Mitarbeiter-Login",
  subline: "Zugang nur für autorisiertes Döner-Personal. Bitte Büro-Kennung eingeben.",
  usernameLabel: "Benutzername",
  usernamePlaceholder: "z. B. m.wagner",
  passwordLabel: "Passwort",
  passwordPlaceholder: "••••••••",
  submit: "Anmelden",
  serverStatus: "Döner-Server erreichbar · Büro Leipzig · v3.0",
  loginFailed: "Anmeldung fehlgeschlagen. Benutzername oder Passwort prüfen, Chef.",
  brandAlt: "Schulz Döner Control",
  profileMenuLabel: "Profilmenü öffnen",
  settings: "Einstellungen",
  tiere: "Döner-Tiere",
  notifications: "Benachrichtigungen",
  adminArea: "Admin-Bereich",
  changePassword: "Passwort ändern",
  logout: "Abmelden",
  logoutFailed: "Abmelden fehlgeschlagen, Chef. Bitte gleich nochmal versuchen.",
  // --- Register page ---
  loginToRegister: "Noch kein Konto? Jetzt registrieren",
  registerEyebrow: "Neuzugang im Döner-Trupp",
  registerHeading: "Konto anlegen",
  registerSubline:
    "Einmal registrieren, dann mitdrehen, Chef. Deine Zugangsdaten wählst du selbst.",
  registerUsernameLabel: "Benutzername",
  registerUsernamePlaceholder: "z. B. m.wagner",
  registerDisplayNameLabel: "Anzeigename",
  registerDisplayNamePlaceholder: "z. B. Markus Wagner",
  registerPayPalHandleLabel: "PayPal.Me-Name (optional)",
  registerPayPalHandlePlaceholder: "z. B. MarkusW",
  registerPasswordLabel: "Passwort",
  registerPasswordPlaceholder: "Mindestens 10 Zeichen",
  registerConfirmPasswordLabel: "Passwort bestätigen",
  registerConfirmPasswordPlaceholder: "••••••••",
  registerSubmit: "Konto anlegen",
  registerPasswordMismatch: "Die Passwörter stimmen nicht überein, Chef.",
  registerFailed: "Konto konnte nicht angelegt werden, Chef. Bitte gleich nochmal versuchen.",
  registerDuplicate: "Dieser Benutzername ist bereits vergeben, Chef.",
  registerCodeInvalid: "Falscher oder fehlender Registrierungscode, Chef.",
  registerSuccessTitle: "Konto erstellt, Chef!",
  registerSuccessBody:
    "Dein Zugang steht. Melde dich jetzt an und reih dich in den Döner-Trupp ein.",
  toLogin: "Zur Anmeldung",
  // Field-level validation copy (mirrors the backend rules).
  registerUsernameRequired: "Pflichtfeld",
  registerUsernameLength: "Benutzername muss 2 bis 64 Zeichen lang sein.",
  registerUsernamePattern: "Nur Buchstaben, Ziffern sowie . _ - sind erlaubt (keine Leerzeichen).",
  registerDisplayNameRequired: "Pflichtfeld",
  registerDisplayNameLength: "Anzeigename darf höchstens 128 Zeichen lang sein.",
  registerPayPalHandlePattern: "Nur Buchstaben und Ziffern sind erlaubt.",
  registerPayPalHandleLength: "PayPal.Me-Name darf höchstens 40 Zeichen lang sein.",
  registerPasswordLength: "Passwort muss mindestens 10 Zeichen lang sein.",
  registerPasswordComplexity: "Passwort braucht mindestens einen Buchstaben und eine Ziffer.",
  registerConfirmPasswordRequired: "Pflichtfeld",
} as const;
