/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthTiereRouteImport } from './routes/_auth/tiere'
import { Route as AuthPasswortAendernRouteImport } from './routes/_auth/passwort-aendern'
import { Route as AuthOrderRouteImport } from './routes/_auth/order'
import { Route as AuthErledigtRouteImport } from './routes/_auth/erledigt'
import { Route as AuthEinstellungenRouteImport } from './routes/_auth/einstellungen'
import { Route as AuthDruckRouteImport } from './routes/_auth/druck'
import { Route as AuthBenachrichtigungenRouteImport } from './routes/_auth/benachrichtigungen'
import { Route as AuthAdminRouteImport } from './routes/_auth/admin'
import { Route as AuthAdminIndexRouteImport } from './routes/_auth/admin/index'
import { Route as AuthAdminTiereRouteImport } from './routes/_auth/admin/tiere'
import { Route as AuthAdminMenueRouteImport } from './routes/_auth/admin/menue'
import { Route as AuthAdminBenutzerRouteImport } from './routes/_auth/admin/benutzer'
import { Route as AuthAdminBenachrichtigungenRouteImport } from './routes/_auth/admin/benachrichtigungen'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTiereRoute = AuthTiereRouteImport.update({
  id: '/tiere',
  path: '/tiere',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPasswortAendernRoute = AuthPasswortAendernRouteImport.update({
  id: '/passwort-aendern',
  path: '/passwort-aendern',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOrderRoute = AuthOrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => AuthRoute,
} as any)
const AuthErledigtRoute = AuthErledigtRouteImport.update({
  id: '/erledigt',
  path: '/erledigt',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEinstellungenRoute = AuthEinstellungenRouteImport.update({
  id: '/einstellungen',
  path: '/einstellungen',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDruckRoute = AuthDruckRouteImport.update({
  id: '/druck',
  path: '/druck',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBenachrichtigungenRoute = AuthBenachrichtigungenRouteImport.update({
  id: '/benachrichtigungen',
  path: '/benachrichtigungen',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminIndexRoute = AuthAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminTiereRoute = AuthAdminTiereRouteImport.update({
  id: '/tiere',
  path: '/tiere',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminMenueRoute = AuthAdminMenueRouteImport.update({
  id: '/menue',
  path: '/menue',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminBenutzerRoute = AuthAdminBenutzerRouteImport.update({
  id: '/benutzer',
  path: '/benutzer',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminBenachrichtigungenRoute =
  AuthAdminBenachrichtigungenRouteImport.update({
    id: '/benachrichtigungen',
    path: '/benachrichtigungen',
    getParentRoute: () => AuthAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AuthAdminRouteWithChildren
  '/benachrichtigungen': typeof AuthBenachrichtigungenRoute
  '/druck': typeof AuthDruckRoute
  '/einstellungen': typeof AuthEinstellungenRoute
  '/erledigt': typeof AuthErledigtRoute
  '/order': typeof AuthOrderRoute
  '/passwort-aendern': typeof AuthPasswortAendernRoute
  '/tiere': typeof AuthTiereRoute
  '/admin/benachrichtigungen': typeof AuthAdminBenachrichtigungenRoute
  '/admin/benutzer': typeof AuthAdminBenutzerRoute
  '/admin/menue': typeof AuthAdminMenueRoute
  '/admin/tiere': typeof AuthAdminTiereRoute
  '/admin/': typeof AuthAdminIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/benachrichtigungen': typeof AuthBenachrichtigungenRoute
  '/druck': typeof AuthDruckRoute
  '/einstellungen': typeof AuthEinstellungenRoute
  '/erledigt': typeof AuthErledigtRoute
  '/order': typeof AuthOrderRoute
  '/passwort-aendern': typeof AuthPasswortAendernRoute
  '/tiere': typeof AuthTiereRoute
  '/': typeof AuthIndexRoute
  '/admin/benachrichtigungen': typeof AuthAdminBenachrichtigungenRoute
  '/admin/benutzer': typeof AuthAdminBenutzerRoute
  '/admin/menue': typeof AuthAdminMenueRoute
  '/admin/tiere': typeof AuthAdminTiereRoute
  '/admin': typeof AuthAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_auth/admin': typeof AuthAdminRouteWithChildren
  '/_auth/benachrichtigungen': typeof AuthBenachrichtigungenRoute
  '/_auth/druck': typeof AuthDruckRoute
  '/_auth/einstellungen': typeof AuthEinstellungenRoute
  '/_auth/erledigt': typeof AuthErledigtRoute
  '/_auth/order': typeof AuthOrderRoute
  '/_auth/passwort-aendern': typeof AuthPasswortAendernRoute
  '/_auth/tiere': typeof AuthTiereRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/admin/benachrichtigungen': typeof AuthAdminBenachrichtigungenRoute
  '/_auth/admin/benutzer': typeof AuthAdminBenutzerRoute
  '/_auth/admin/menue': typeof AuthAdminMenueRoute
  '/_auth/admin/tiere': typeof AuthAdminTiereRoute
  '/_auth/admin/': typeof AuthAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/admin'
    | '/benachrichtigungen'
    | '/druck'
    | '/einstellungen'
    | '/erledigt'
    | '/order'
    | '/passwort-aendern'
    | '/tiere'
    | '/admin/benachrichtigungen'
    | '/admin/benutzer'
    | '/admin/menue'
    | '/admin/tiere'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/benachrichtigungen'
    | '/druck'
    | '/einstellungen'
    | '/erledigt'
    | '/order'
    | '/passwort-aendern'
    | '/tiere'
    | '/'
    | '/admin/benachrichtigungen'
    | '/admin/benutzer'
    | '/admin/menue'
    | '/admin/tiere'
    | '/admin'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/register'
    | '/_auth/admin'
    | '/_auth/benachrichtigungen'
    | '/_auth/druck'
    | '/_auth/einstellungen'
    | '/_auth/erledigt'
    | '/_auth/order'
    | '/_auth/passwort-aendern'
    | '/_auth/tiere'
    | '/_auth/'
    | '/_auth/admin/benachrichtigungen'
    | '/_auth/admin/benutzer'
    | '/_auth/admin/menue'
    | '/_auth/admin/tiere'
    | '/_auth/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tiere': {
      id: '/_auth/tiere'
      path: '/tiere'
      fullPath: '/tiere'
      preLoaderRoute: typeof AuthTiereRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/passwort-aendern': {
      id: '/_auth/passwort-aendern'
      path: '/passwort-aendern'
      fullPath: '/passwort-aendern'
      preLoaderRoute: typeof AuthPasswortAendernRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/order': {
      id: '/_auth/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof AuthOrderRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/erledigt': {
      id: '/_auth/erledigt'
      path: '/erledigt'
      fullPath: '/erledigt'
      preLoaderRoute: typeof AuthErledigtRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/einstellungen': {
      id: '/_auth/einstellungen'
      path: '/einstellungen'
      fullPath: '/einstellungen'
      preLoaderRoute: typeof AuthEinstellungenRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/druck': {
      id: '/_auth/druck'
      path: '/druck'
      fullPath: '/druck'
      preLoaderRoute: typeof AuthDruckRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/benachrichtigungen': {
      id: '/_auth/benachrichtigungen'
      path: '/benachrichtigungen'
      fullPath: '/benachrichtigungen'
      preLoaderRoute: typeof AuthBenachrichtigungenRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/': {
      id: '/_auth/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthAdminIndexRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/tiere': {
      id: '/_auth/admin/tiere'
      path: '/tiere'
      fullPath: '/admin/tiere'
      preLoaderRoute: typeof AuthAdminTiereRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/menue': {
      id: '/_auth/admin/menue'
      path: '/menue'
      fullPath: '/admin/menue'
      preLoaderRoute: typeof AuthAdminMenueRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/benutzer': {
      id: '/_auth/admin/benutzer'
      path: '/benutzer'
      fullPath: '/admin/benutzer'
      preLoaderRoute: typeof AuthAdminBenutzerRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/benachrichtigungen': {
      id: '/_auth/admin/benachrichtigungen'
      path: '/benachrichtigungen'
      fullPath: '/admin/benachrichtigungen'
      preLoaderRoute: typeof AuthAdminBenachrichtigungenRouteImport
      parentRoute: typeof AuthAdminRoute
    }
  }
}

interface AuthAdminRouteChildren {
  AuthAdminBenachrichtigungenRoute: typeof AuthAdminBenachrichtigungenRoute
  AuthAdminBenutzerRoute: typeof AuthAdminBenutzerRoute
  AuthAdminMenueRoute: typeof AuthAdminMenueRoute
  AuthAdminTiereRoute: typeof AuthAdminTiereRoute
  AuthAdminIndexRoute: typeof AuthAdminIndexRoute
}

const AuthAdminRouteChildren: AuthAdminRouteChildren = {
  AuthAdminBenachrichtigungenRoute: AuthAdminBenachrichtigungenRoute,
  AuthAdminBenutzerRoute: AuthAdminBenutzerRoute,
  AuthAdminMenueRoute: AuthAdminMenueRoute,
  AuthAdminTiereRoute: AuthAdminTiereRoute,
  AuthAdminIndexRoute: AuthAdminIndexRoute,
}

const AuthAdminRouteWithChildren = AuthAdminRoute._addFileChildren(
  AuthAdminRouteChildren,
)

interface AuthRouteChildren {
  AuthAdminRoute: typeof AuthAdminRouteWithChildren
  AuthBenachrichtigungenRoute: typeof AuthBenachrichtigungenRoute
  AuthDruckRoute: typeof AuthDruckRoute
  AuthEinstellungenRoute: typeof AuthEinstellungenRoute
  AuthErledigtRoute: typeof AuthErledigtRoute
  AuthOrderRoute: typeof AuthOrderRoute
  AuthPasswortAendernRoute: typeof AuthPasswortAendernRoute
  AuthTiereRoute: typeof AuthTiereRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminRoute: AuthAdminRouteWithChildren,
  AuthBenachrichtigungenRoute: AuthBenachrichtigungenRoute,
  AuthDruckRoute: AuthDruckRoute,
  AuthEinstellungenRoute: AuthEinstellungenRoute,
  AuthErledigtRoute: AuthErledigtRoute,
  AuthOrderRoute: AuthOrderRoute,
  AuthPasswortAendernRoute: AuthPasswortAendernRoute,
  AuthTiereRoute: AuthTiereRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
